alphaTao-v0.9:
  is_pretrain: false
  pretrain_steps: 5000
  pretrain_file: 'minimax_data1.pkl'
  is_training: true
  optimizer_batch_size: 64
  inference_batch_size: 64
  replay_memory_size: 2000
  exist_model_name: 'alphaTao-v0.9'
  run_dir: 'runs\alphaTao-v0.9'
  restore_dir: 'runs\alphaTao-v0.9'
  exploration_factor: 1.5
  is_self_play: true
  self_play_num: 800
  board_size: 15
  residual_blocks: 10
  update_freq: 2
  warmup_steps: 0
  restore_epoch: 25
  search_num: 400
  is_continue_training: true
  is_muti_optimizer: true
  num_optimizer: 5
  lr: 0.00005

alphaTao-v0.4-run:
  is_training: false
  optimizer_batch_size: 64
  inference_batch_size: 64
  replay_memory_size: 100000
  exist_model_name: 'alphaTao-v0.4'
  run_dir: 'runs\alphaTao-v0.4'
  restore_dir: 'runs\alphaTao-v0.4'
  warmup_steps: 0
  exploration_factor: 5
  is_self_play: false
  self_play_num: 1000
  board_size: 15
  residual_blocks: 10
  update_freq: 5
  restore_epoch: 5
  search_num: 512
  is_continue_training: false

test1:
  is_training: true
  optimizer_batch_size: 64
  inference_batch_size: 64
  replay_memory_size: 100000
  exist_model_name: 'test1'
  run_dir: 'runs\test1'
  restore_dir: 'runs\test1'
  restore_epoch: 4
  exploration_factor: 1.5
  is_self_play: true
  self_play_num: 100
  board_size: 15
  residual_blocks: 10
  update_freq: 2
  search_num: 512
  is_continue_training: false
  is_muti_optimizer: true
  num_optimizer: 10

test_overfit:
  is_training: true
  optimizer_batch_size: 64
  inference_batch_size: 64
  replay_memory_size: 100000
  exist_model_name: 'test_overfit'
  run_dir: 'runs\test_overfit'
  restore_dir: 'runs\test_overfit'
  restore_epoch: 4
  exploration_factor: 1
  warmup_steps: 0
  is_self_play: true
  self_play_num: 100
  board_size: 8
  residual_blocks: 10
  update_freq: 2
  search_num: 400
  is_continue_training: false
  is_muti_optimizer: true
  num_optimizer: 10
  lr: 0.0005

test2:
  is_training: true
  optimizer_batch_size: 64
  inference_batch_size: 64
  replay_memory_size: 100000
  exist_model_name: 'test1'
  run_dir: 'runs\test1'
  restore_dir: 'runs\test2'
  restore_epoch: 4
  exploration_factor: 1.5
  is_self_play: true
  self_play_num: 1000
  board_size: 15
  residual_blocks: 10
  update_freq: 2
  search_num: 512
  is_continue_training: true